# Generated by Django 4.2 on 2023-04-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student_student_user_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
